name: Testing Farm request
on:
  pull_request:

# The concurrency key is used to prevent multiple workflows from running at the same time
concurrency:
  group: my-concurrency-group
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule test on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v4
        with:
          api_key: ${{ secrets.TF_SECRET }}
          compose: Fedora-42
          tmt_hardware: '{"virtualization": {"is-supported": true}}'
